export { EditUserInfoPage } from './EditUserInfoPage'
export { Home } from './HomePage'
export { CreatePosts } from './CreatePostsPage/page'
export { LoginForm } from './SignIn/ui/LoginForm'
export { RegistrationForm } from './SignIn/ui/RegistrationForm/RegistrationForm'
